my_costmap:
  plugins: 
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_foot_point
  #footprint: [[0.4,0.4], [-0.65,0.4], [-0.65,-0.4], [0.4,-0.4]]
  footprint: [[-0.55, 0], [-0.5, 0.38], [0, 0.55], [0.48, 0.38], [0.55, 0], [0.48, -0.38], [0, -0.55], [-0.5, -0.38]]
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.1
  update_frequency: 20.0
  publish_frequency: 20.0

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: camera_link
      topic: scan
      data_type: LaserScan
      marking: true
      clearing: true
      obstacle_range : 5.5
      raytrace_range : 6.0
  inflation_layer:
    inflation_radius: 2
    cost_scaling_factor : 5